### ISSUE TITLE
Shop's Item(s) result JSON is incomplete

### ISSUE THREAD

**Issue by Raiondesu** [InnoDevelopment/Innopoints#1]
Information returned in a GetItem function is incomplete: it lacks fields such as `image_link`, `title` and `category`.

It's really not comfortable, since for displaying the full information about the item I need to concatenate the two objects: one returned form `GetItems` and one returned from `GetItem`. It's not easily done and requires some experience in **bicycle engineering**. ;)

So, it would be much nicer if the result of `GetItems` returned all the info about every item (with according removal of `GetItem`) - (1). Or - make  `GetItem` return full information about the desired item - (2).

**Comment by Muzicius** [comment]
Fixed. Response: 

```
{
  "status": "ok",
  "result": {
    "combinations": {
      "{\"Size\"=>\"S\", \"Colour\"=>\"Black\"}": {
        "id": 1,
        "quantity": 2
      },
      "{\"Size\"=>\"M\", \"Colour\"=>\"Black\"}": {
        "id": 2,
        "quantity": 2
      },
      "{\"Size\"=>\"S\", \"Colour\"=>\"Yellow\"}": {
        "id": 3,
        "quantity": 2
      },
      "{\"Size\"=>\"M\", \"Colour\"=>\"Yellow\"}": {
        "id": 4,
        "quantity": 2
      }
    },
    "category": {
      "id": 1,
      "title": "Clothes"
    },
    "title": "Polo shirt",
    "image_link": "/public/items/1.jpg",
    "id": 1,
    "price": 900,
    "possible_joint_purchase": false,
    "options": [
      {
        "title": "Size",
        "values": [
          "M",
          "S"
        ]
      },
      {
        "title": "Colour",
        "values": [
          "Black",
          "Yellow"
        ]
      }
    ]
  }
}
```
